<a href="https://colab.research.google.com/github/KinjalBiswas-2005/python-applications/blob/main/1ST_PYTHON_PROGRAMMING22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('welcome to python programming')

welcome to python programming


In [ ]:
print('hello',end='')
print("cse")

hellocse


In [ ]:
a=100
print("a=",a)

a= 100


In [ ]:
n=input('Enter your name')
print('Myself :', n)

Enter your nameKinjal
Myself : Kinjal


In [ ]:
print(2+3)
print

5
23


In [ ]:
# Complex Number
a=12+15j
print('a=' ,a)
print(a.real)
print(a.imag)

a= (12+15j)
12.0
15.0


In [ ]:
a=0b111
print('a =', a)
b=0xaa
print('b =', b)

a = 7
b = 170


In [ ]:
from re import T
# to check data type
a=100
b=10.55
c='ABIT'
d=True
print('Type of a=',type(a))
print('Type of b=',type(b))
print('Type of c=',type(c))
print('Type of d=',type(d))


Type of a= <class 'int'>
Type of b= <class 'float'>
Type of c= <class 'str'>
Type of d= <class 'bool'>


In [ ]:
print('Hello cse group-ii')

Hello cse group-ii


In [ ]:
#Using of + operator
a = int(input('Enter 1st no.'))
b = int(input('Enter 2nd no.'))
c = a + b
print(c)

Enter 1st no.22
Enter 2nd no.33
55


In [ ]:
a =123
print(type(a))
b ="Hello"
print(type(b))
c=12.3
print(type(c))
d=True
print(type(d))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'bool'>


In [ ]:
from binascii import b2a_base64
#Arithmetic Operators
a = 2
b = 5
c = a+b
print('a+b=' ,c)
d = a-b
print('a-b=' ,d)
e = a*b
print('a*b=' ,e)
f = a/b
print('a/b=' ,f)
h = a//b
print('a-b=' ,h)
g = a%b
print('a%b=' ,g)
i = a**b
print('a**b=' ,i)


a+b= 7
a-b= -3
a*b= 10
a/b= 0.4
a-b= 0
a%b= 2
a**b= 32


In [ ]:
a = 8
b = 5
d = a != b
print('a != b=' ,d)

a != b= True


In [ ]:
#Bitwise - Shift operator
a = 4
b = 2
d = a & b
print('a & b=' ,d)
f= a << b
print('a << b=',f)

a & b= 0
a << b= 16


In [ ]:
a=2
b=5
a+=b
print('a =',a)
print('b =',b)

a = 7
b = 5


In [ ]:
#Special Operator
a=5
b=5
d = a is b
print('a is b =',d)
d = a is not b
print('a is not b =',d)

a is b = True
a is not b = False


In [ ]:
# in Operator
a ="Hello"
b ='l'
c = b in a
print('b in a =', c)
d = b not in a
print('b not in a =',d)

b in a = True
b not in a = False


In [ ]:
# input a no and check even.
a=int(input('Enter a number'))
if a%2==0:
  print('Even number')
else:
   print('Odd number')

Enter a number5
Odd number


In [ ]:
# input a no and check maximum.
a=int(input('Enter a number'))
b=int(input('Enter a number'))
if a>b:
  print('a is max')
else:
  print('b is min')

Enter a number26
Enter a number34
b is min


In [ ]:
number=int(input("Enter the number?"))
if number==10:
  print("number is equal to 10")
elif number==50:
  print("number is equal to 50")
elif number==100:
  print("number is equal to 100")
else:
  print("number is not equal to 10,50 or 100")



Enter the number?100
number is equal to 100


In [ ]:
str = 'PYTHON'
for i in str:
  print(i)

P
Y
T
H
O
N


In [ ]:
for i in range(1,11):
  print(i,end ="")


12345678910

In [ ]:

n = int(input('n = ?'))
c=0
for i in range (1,n+1):
  if(i%2==1):
    c=c+1
    print(i,end=',')
print('No of ODD=',c)

n = ?10
1,3,5,7,9,No of ODD= 5


In [ ]:
# while loop
n = 1
while n<=10:
  print(n)
  n=n+1


1
2
3
4
5
6
7
8
9
10


In [ ]:
#while loop
num=int(input('Enter the no.s'))
rev=0
while num!=0:
  d=num%10
  rev=rev*10+d
  num//=10
  print('Reverse is'+str(rev))

Enter the no.s34567
Reverse is7
Reverse is76
Reverse is765
Reverse is7654
Reverse is76543


In [ ]:
#to find the reverse of a number
n=int(input('Enter a number'))
c=0
reverse=0
while(n>0):
  reverse=reverse+n%10
n=n/10
print('The reverse of the number is',reverse)

In [ ]:
rows=6
for i in range(rows):
  for j in range(i):
    print(i,end='')
  print('')


1
22
333
4444
55555


In [ ]:
rows=6
b=0
for i in range(rows,0,-1):
  b +=1
  for j in range(1,i,+1):
    print(b,end='')
  print('\r')

11111
2222
333
44
5



In [ ]:
n=5
for i in range(n,0,-1):
 b=i
 for j in range(0,i):
  print(b,end='')
 print('\r')

55555
4444
333
22
1


In [ ]:
for i in range(5,0,-1):
  for j in range(i,6):
    print(i,end='')
  print('')

5
44
333
2222
11111


In [ ]:
rows=6
for i in range(1,6):
  print(str(i)*(i))


for i in range(4,0,-1):
    print(str(i)*(i))

1
22
333
4444
55555
4444
333
22
1


In [ ]:
rows=6
for i in range(rows,0,-1):
  for j in range(0,i+1):
    print(j,end='')
  print('')

0123456
012345
01234
0123
012
01


In [ ]:
rows=5
num=rows
for i in range(rows,0,-1):
  for j in range(0,i):
    print(num,end='')
  print('')

55555
5555
555
55
5


In [ ]:
rows=6
for i in range(1,rows):
  for j in range(1,i+1):
    sq=i*j
    print(i*j,end='')
  print('\r')

1
24
369
481216
510152025


In [ ]:
rows=8
for i in range(1,rows+1):
  for j in range(1,i+1):
    sq=i*j
    print(i*j,end=" ")
  print('\r')

1 
2 4 
3 6 9 
4 8 12 16 
5 10 15 20 25 
6 12 18 24 30 36 
7 14 21 28 35 42 49 
8 16 24 32 40 48 56 64 


In [ ]:
rows=70
for i in range(65,rows):
  for j in range(65,i+1):
    print(chr(i),end=" ")
  print(" ")

A  
B B  
C C C  
D D D D  
E E E E E  


In [ ]:
# To find AREA and PERIMETER
# Triangle AREA=1/2x b x h ,PERIMETER=a+b+c
b = int(input('Enter b = ?'))
h = int(input('Enter h= ?'))
area = 0.5 * b * h
print('AREA OF TRIANGLE =',area)
# Triangle PERIMETER= a + b + c
a = int(input('Enter a = ?'))
b = int(input('Enter b = ?'))
c = int(input('Enter c = ?'))
perimeter=a*b*c
print('PERIMETER OF TRIANGLE =',perimeter)

Enter b = ?5
Enter h= ?6
AREA OF TRIANGLE = 15.0
Enter a = ?7
Enter b = ?8
Enter c = ?4
PERIMETER OF TRIANGLE = 224


In [ ]:
for var in "ABIT":
  if var=="B":
    continue
  print(var)

A
I
T


In [ ]:
for i in range(10):
   print(i)
   if i == 2:
    break

0
1
2


In [ ]:
x = abs(-7.25)
print(x)


7.25


In [ ]:
list = [0,2,2]
a = all(list)
print(a)

False


In [ ]:
tuple = (0,1,False)
a = any(tuple)
print(a)

True


In [ ]:
a = ascii("Mostly Sane")
print(a)


'Mostly Sane'


In [ ]:
a = bin(30)
print(a)

0b11110


In [ ]:
a = bool(22)
print(a)

True


In [ ]:
a = ('jhon','ann','sia')
b = enumerate(a)
print(b)

In [ ]:
class Student:
 name = "Ann"
 age = 28
 country = "USA"
x = getattr(Student,'age')
print(x)

28


In [ ]:
a = dict(name="Jaydon",mob=1834567,country="Canada")
print(a)

{'name': 'Jaydon', 'mob': 1834567, 'country': 'Canada'}


In [ ]:
class User:
  name="Jaydon"
  mob=1543678
  country="Canada"
print(dir(User))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'country', 'mob', 'name']


In [ ]:
a=globals()
print(a)

{'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, '__loader__': None, '__spec__': None, '__builtin__': <module 'builtins' (built-in)>, '__builtins__': <module 'builtins' (built-in)>, '_ih': ['', "a = dict('name':'Jaydon','mob':1834567,'country':'Canada')\nprint(a)", "a = dict('name': 'Jaydon','mob': 1834567,'country': 'Canada')\nprint(a)", 'a = dict(name:"Jaydon",mob: 1834567,country:"Canada")\nprint(a)', 'a = dict(name="Jaydon",mob=1834567,country="Canada")\nprint(a)', 'class User:\n  name="Jaydon"\n  mob=1543678\n  country="Canada"\n  print(dir(User))', 'class User:\n  name="Jaydon"\n  mob=1543678\n  country="Canada"\nprint(dir(User))', 'a=globals()\nprint(a)'], '_oh': {}, '_dh': ['/content'], 'In': ['', "a = dict('name':'Jaydon','mob':1834567,'country':'Canada')\nprint(a)", "a = dict('name': 'Jaydon','mob': 1834567,'country': 'Canada')\nprint(a)", 'a = dict(name:"Jaydon",mob: 1834567,country:"Canada")\nprint(

In [ ]:
a=format(1.5,'%')
print(a)

150.000000%


In [ ]:
score=[15,10,20,17,26,42]
def customFunc(a):
  if a<20:
   return False
  else:
    return True
players=filter(customFunc,score)
for a in players:
 print(a)

20
26
42


In [ ]:
class speed:
  kmph=136
class car(speed):
  name="BMW"
  speed=speed
x=issubclass(car,speed)
print(x)


True


In [ ]:
x=iter(["jhon","lisa","maria","ava"])
print(next(x))
print(next(x))
print(next(x))
print(next(x))

jhon
lisa
maria
ava


In [ ]:
a=bytes(22)
print(a)

b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'


In [ ]:
a=compile('print(45)','test','eval')
exec(a)

45


In [ ]:
# User defined Function
def show():
  print('HELLO CSE')
show()

HELLO CSE


In [ ]:
# Passing Parameters in User Defined Function
def ADD(a,b):
  c=a+b
  print('SUM OF TWO NUMBERS=',c)
ADD(10,20)

SUM OF TWO NUMBERS= 30


In [ ]:
# Passing Parameters in User Defined Function Using KEYBOARD
def ADD(a,b):
  c=a+b
  print('SUM OF TWO NUMBERS=',c)
ADD(10,20)
p=int(input("Enter 1st no.= ?"))
q=int(input("Enter 2nd no.= ?"))
ADD(p,q)

SUM OF TWO NUMBERS= 30
Enter 1st no.= ?40
Enter 2nd no.= ?50
SUM OF TWO NUMBERS= 90


In [ ]:
# Using Return Statement in User Defined Function.
def sumofn(n):
  s=0
  for i in range(1,n+1):
    s=s+i
  return(s)
m=int(input("Enter n value= ?"))
print('Sum of N=',sumofn(m))


Enter n value= ?6
Sum of N= 21


In [ ]:
def star(p,q):
 number=1
 for i in range(1,p):
    for j in range(1,q):
      if(j<=i):
         print(number,end=" ")
         number+=1
    print()


m=int(input('Enter the no.for row= ?'))
n=int(input('Enter the no. for column= ?'))
star(m,n)


Enter the no.for row= ?5
Enter the no. for column= ?4
1 
2 3 
4 5 6 
7 8 9 


In [ ]:
list=['P','Y','T','H','O','N']
print(list)
print(list[2:6])
print(list[:4])
print(list[4:])

['P', 'Y', 'T', 'H', 'O', 'N']
['T', 'H', 'O', 'N']
['P', 'Y', 'T', 'H']
['O', 'N']


In [ ]:
list=[10,20,30,40,50,60,70,80,90]
print(list[2:6])

[30, 40, 50, 60]


In [ ]:
# Triangle Area
b=int(input('Enter b:'))
h=int(input('Enter h:'))
area=0.5*b*h
print('Area of triangle is=',area)
# Triangle perimeter
a=int(input('Enter a:'))
b=int(input('Enter b:'))
c=int(input('Enter c:'))
perimeter=a*b*c
print('perimeter of a triangle is=',perimeter)

Enter b:5
Enter h:6
Area of triangle is= 15.0
Enter a:8
Enter b:9
Enter c:4
perimeter of a triangle is= 288


In [ ]:
# Rectangle Area
l=int(input('Enter l:'))
b=int(input('Enter b:'))
area=l*b
print('Area of rectangle is=',area)
# Rectangle perimeter
l=int(input('Enter l:'))
b=int(input('Enter b:'))
perimeter=2*(l+b)
print('Perimeter of rectangle=',perimeter)


Enter l:8
Enter b:9
Area of rectangle is= 72
Enter l:34
Enter b:45
Perimeter of rectangle= 158


In [ ]:
# square Area
s1=int(input('Enter s1:'))
s2=int(input('Enter s2:'))
area=s1*s2
print('Area of square is=',area)
# square perimeter
s=int(input('Enter s:'))
perimeter=4*s
print('Perimeter of square=',perimeter)


Enter s1:45
Enter s2:67
Area of square is= 3015
Enter s:89
Perimeter of square= 356


In [ ]:
# Circle Area
r=int(input('Enter r:'))
area=3.14*r*r
print('Area of circle is=',area)
# circle perimeter
r=int(input('enter r:'))
perimeter=2*3.14*r
print('Perimeter of circle is=',perimeter)

Enter r:6
Area of circle is= 113.03999999999999
enter r:8
Perimeter of circle is= 50.24


In [ ]:
# Ellipse Area
b=int(input('Enter b:'))
area=3.14*b
print('Area of ellipse is=',area)
# Ellipse perimeter
a=int(input('Enter a:'))
b=int(input('Enter b:'))
perimeter=3.14*(a+b)
print('Perimeter of ellipse is=',perimeter)


Enter b:8
Area of ellipse is= 25.12
Enter a:5
Enter b:7
Perimeter of ellipse is= 37.68


In [ ]:
# Parallelogram Area
b=int(input('Enter b:'))
h=int(input('Enter h:'))
Area=b*h
print('Area of parallelogram is=',area)
# Parallelogram Perimeter
a=int(input('Enter a:'))
b=int(input('Enter b:'))
perimeter=2*(a+b)
print('Perimeter of parallelogram=',perimeter)

Enter b:9
Enter h:4
Area of parallelogram is= 25.12
Enter a:8
Enter b:6
Perimeter of parallelogram= 28


In [ ]:
# Rhombus Area
d1=int(input('Enter d1:'))
d2=int(input('Enter d2:'))
Area=1/2*(d1*d2)
print('Area of rhombus=',area)
# Rhombus Perimeter
a=int(input('Enter a:'))
Perimeter=4*a
print('Perimeter of rhombus=',perimeter)


Enter d1:3
Enter d2:8
Area of rhombus= 25.12
Enter a:6
Perimeter of rhombus= 28


In [ ]:
# Trapezium Area
a=int(input('Enter a:'))
b=int(input('Enter b:'))
h=int(input('Enter h:'))
Area=1/2*(a+b)*h
print('Area of trapezium is=',area)
# Trapezium perimeter
a=int(input('Enter a:'))
b=int(input('Enter b:'))
c=int(input('Enter c:'))
d=int(input('Enter d:'))
perimeter=a+b+c+d
print('Perimeter of trapezium is=',perimeter)

Enter a:9
Enter b:8
Enter h:6
Area of trapezium is= 25.12
Enter a:8
Enter b:9
Enter c:4
Enter d:6
Perimeter of trapezium is= 27


In [ ]:
# Cube volume
s=int(input('Enter s:'))
volume=s*s*s
print('Volume of a cube is=',volume)
# Cube surface area
s=int(input('Enter s:'))
surface_area=6*s*s
print('surface area of a cube is=',surface_area)

Enter s:56
Volume of a cube is= 175616
Enter s:45
surface area of a cube is= 12150


In [ ]:
# Cuboid volume
l=int(input('Enter l:'))
w=int(input('Enter w:'))
h=int(input('Enter h:'))
volume=l*w*h
print('volume of cuboid is=',volume)
# Cuboid surface area
l=int(input('Enter l:'))
w=int(input('Enter w:'))
h=int(input('Enter h:'))
surface_area=(2*l*h)+(2*l*w)+(2*w*h)
print('surface area of cuboid is=',surface_area)

Enter l:3
Enter w:8
Enter h:5
volume of cuboid is= 120
Enter l:6
Enter w:9
Enter h:8
surface area of cuboid is= 348


In [ ]:
# Regular tetrahedron volume
import math
b=int(input('Enter b:'))
volume=(b*b*b)/(6*math.sqrt(2))
print('volume of a regular tetrahedron is=',volume)
#Regular tetrahedron surface area
b=int(input('Enter b:'))
surface_area=math.sqrt(3)*b*b
print('surface area of regular tetrahedron is=',surface_area)

Enter b:5
volume of a regular tetrahedron is= 14.731391274719739
Enter b:8
surface area of regular tetrahedron is= 110.85125168440814


In [ ]:
# Pyramids volume
a=int(input('Enter a:'))
h=int(input('Enter h:'))
volume=0.3*a*h
print('volume of a pyramid is=',volume)

Enter a:8
Enter h:9
volume of a pyramid is= 21.599999999999998


In [ ]:
# Square pyramid volume
s=int(input('Enter s:'))
h=int(input('Enter h:'))
volume=1/3*s*s*h
print('volume of a square pyramid is=',volume)
# Square Pyramid surafce area
s=int(input('Enter s:'))
h=int(input('Enter h:'))
surface_area=(s*s)+(2*s*h)
print('Surface area of a square pyramid is=',surface_area)

Enter s:8
Enter h:7
volume of a square pyramid is= 149.33333333333331
Enter s:9
Enter h:5
Surface area of a square pyramid is= 171


In [ ]:
# prisms volume
a=int(input('Enter a:'))
h=int(input('Enter h:'))
volume=a*h
print('volume of a prism is=',volume)
# Prisms surface area
a=int(input('Enter a:'))
h=int(input('Enter h:'))
p=int(input('Enter p:'))
surface_area=2*a+(h*p)
print('surface area of a prism is=',surface_area)

Enter a:8
Enter h:9
volume of a prism is= 72
Enter a:7
Enter h:5
Enter p:4
surface area of a prism is= 34


In [ ]:
# Triangular prism volume
l=int(input('Enter l:'))
b=int(input('Enter b:'))
h=int(input('Enter h:'))
volume=l*b*h
print('volume of a triangular prsim is=',volume)
# Triangular prism surface area
l=int(input('Enter l:'))
b=int(input('Enter b:'))
h=int(input('Enter h:'))
s=int(input('Enter s:'))
surface_area=(b*h)+(2*l*s)+(l*b)
print('surface area of a tringular prism is',surface_area)

Enter l:6
Enter b:9
Enter h:7
volume of a triangular prsim is= 378
Enter l:8
Enter b:4
Enter h:3
Enter s:5
surface area of a tringular prism is 124


In [ ]:
# Spheres volume
n=int(input('Enter n:'))
r=int(input('Enter r:'))
volume=4/3*(n*r*r*r)
print('volume of a sphere is=',volume)
# Spheres surface area
n=int(input('Enter n:'))
r=int(input('Enter r:'))
surface_area=4*n*r*r
print('surface area of a sphere is=',surface_area)

Enter n:6
Enter r:9
volume of a sphere is= 5832.0
Enter n:8
Enter r:5
surface area of a sphere is= 800


In [ ]:
# Right circular cone volume
n=int(input('Enter n:'))
r=int(input('Enter r:'))
h=int(input('Enter h:'))
volume=1/3*(n*r*r*h)
print('volume of a right circular cone is=',volume)
# Right circular cone surface area
n=int(input('Enter n:'))
r=int(input('Enter r:'))
s=int(input('Enter s:'))
surface_area=n*r*(r+s)
print('Surface area of a right circular cone is=',surface_area)

Enter n:6
Enter r:7
Enter h:9
volume of a right circular cone is= 882.0
Enter n:7
Enter r:6
Enter s:4
Surface area of a right circular cone is= 420


In [ ]:
# Right cylinder volume
n=int(input('Enter n:'))
r=int(input('Enter r:'))
h=int(input('Enter h:'))
volume=n*r*r*h
print('volume of a right cylinder is=',volume)
# Right cylinder Surface area
n=int(input('Enter n:'))
r=int(input('Enter r:'))
h=int(input('Enter h:'))
surface_area=2*n*r*(r+h)
print('surface area of a right cylinder is=',surface_area)

Enter n:9
Enter r:6
Enter h:4
volume of a right cylinder is= 1296
Enter n:8
Enter r:5
Enter h:3
surface area of a right cylinder is= 640


In [ ]:
# Swapping without using third variable
x=43
y=67
print('After swapping')
print('Value of x:',y)
print('Value of y:',x)

After swapping
Value of x: 67
Value of y: 43


In [ ]:
# Swapping using third variable
x=89
y=78
temp=x
x=y
y=temp
print('After swapping')
print('Value of x:',x)
print('Value of y:',y)


After swapping
Value of x: 78
Value of y: 89


In [ ]:
# Reverse without using loop
rev=0
base=1;
def reverse(num):
 global rev
 global base
 if(num>0):
  reverse((int)(num/10))
  rev+=(num%10)*base
  base*=10
 return rev
num=7654321
print(reverse(num))


1234567


In [ ]:
# Neon number or not
sum=0
num=int(input('Enter the no.'))
square=num*num
while(square!=0):
  digit=square%10
  sum=sum+digit
  square=square//10
if(num==sum):
  print(str(num)+' is neon number')
else:
  print(str(num)+'is not neon number')


Enter the no.9
9 is neon number


In [ ]:
# Automorphic or not
num=int(input('Enter the number'))
square=pow(num,2)
mod=pow(10,len(str(num)))
if (square%mod==num):
  print('It is an automorphic number')
else:
  print('It is not an automorphic number')

Enter the number376
It is an automorphic number


In [ ]:
# Perfect number or not
num = int(input('Enter the no'))
sum=0
for i in range(1,num):
  if(num%i==0):
   sum=sum+i
if(sum==num):
  print('It is a perfect number')
else:
  print('It is not a perfect number')

Enter the no28
It is a perfect number


In [ ]:
# Abundant number or not
num=int(input('Enter the number'))
sum=1
for i in range(2,num):
  if(num%i==0):
   sum=sum+i
if(sum>num):
  print('It is an abundant number')
else:
  print('It is not an abundant number')

Enter the number16
It is not an abundant number


In [ ]:
# Display neon number from 1 to 1000
print("Enter a range:")
range1=int(input())
range2=int(input())
print("Neon numbers between ",range1," and ",range2," are: ")
for i in range(range1,range2+1):
    sqr =i*i
    # Sum of digit
    sum = 0
    while sqr != 0:
       rem = sqr % 10
       sum += rem
       sqr //= 10

    if sum == i:
        print(i,end=" ")

Enter a range:
1
1000
Neon numbers between  1  and  1000  are: 
1 9 

In [ ]:
# Spy number or not
num = int(input('Enter the number'))
sum=0
product=1
while(num>0):
  d=num%10
  sum=sum+d
  product=product*d
  num=num//10
if(sum==product):
  print('It is a spy number')
else:
  print('It is not a spy number')

Enter the number123
It is a spy number


In [ ]:
# Perfect square or not
import math
num=int(input('Enter the number'))
sqrt_num=math.sqrt(num)
if sqrt_num.is_integer():
  print('The no. is perfect square')
else:
  print('The no. is not perfect square')

Enter the number225
The no. is perfect square


In [ ]:
# Prime number or not
num=int(input('Enter the number'))
flag = False
if(num == 1):
  print(num,"is not a prime number")
elif(num > 1):
  for i in range(2, num):
      if(num % i)==0:
        flag = True
        break
  if flag:
    print(num, "It is not a prime number")
  else:
    print(num, "It is a prime number")


Enter the number9
9 It is not a prime number


In [ ]:
my_list = ["orange","apple","banana","strawberry"]
print(my_list)
print(type(my_list))
print(len(my_list))
my_list.append('grapes')
print(my_list)
my_list.extend('pineapple')
print(my_list)
my_list.remove('grapes')
print(my_list)
my_list.pop(3)
print(my_list)
del my_list[1]
print(my_list)

['orange', 'apple', 'banana', 'strawberry']
<class 'list'>
4
['orange', 'apple', 'banana', 'strawberry', 'grapes']
['orange', 'apple', 'banana', 'strawberry', 'grapes', 'p', 'i', 'n', 'e', 'a', 'p', 'p', 'l', 'e']
['orange', 'apple', 'banana', 'strawberry', 'p', 'i', 'n', 'e', 'a', 'p', 'p', 'l', 'e']
['orange', 'apple', 'banana', 'p', 'i', 'n', 'e', 'a', 'p', 'p', 'l', 'e']
['orange', 'banana', 'p', 'i', 'n', 'e', 'a', 'p', 'p', 'l', 'e']


In [ ]:
my_list = ["orange",10,"banana",True]
print(my_list[0])
print(my_list[-1])
print(my_list[-2])
print(my_list[1:3])
if("orange"in my_list):
  print('yes it is in the list')
else:
  print('No it is not in list')
my_list[3]=["cherry"]
print(my_list)
my_list.insert(3,"mango")
print(my_list)

orange
True
banana
[10, 'banana']
yes it is in the list
['orange', 10, 'banana', ['cherry']]
['orange', 10, 'banana', 'mango', ['cherry']]


In [ ]:
my_list = ["orange","apple","banana","strawberry"]
print(my_list)
for i in my_list:
  print(i)

['orange', 'apple', 'banana', 'strawberry']
orange
apple
banana
strawberry


In [ ]:
my_list = ["orange","apple","banana","strawberry"]
print(my_list)
i = 0
while i<len(my_list):
    print(my_list[i])
    i+=1



['orange', 'apple', 'banana', 'strawberry']
orange
apple
banana
strawberry


In [ ]:
#python programming for sorting
list=[5,2,-3,7,99,33,71,57]
n=len(list)
for i in range(n):
  for j in range(0,n-i-1):
    if(list[j]>list[j+1]):
      k=list[j]
      list[j]=list[j+1]
      list[j+1]=k
print(list)
list.sort()
print(list)

[-3, 2, 5, 7, 33, 57, 71, 99]
[-3, 2, 5, 7, 33, 57, 71, 99]


In [ ]:
lista=[5,2,-3.7,99,33,71,57]
n=len(lista)
for i in range(n):
  for j in range(0,n-i-1):
    if(list[j]>list[j+1]):
      k=list[j]
      list[j]=list[j+1]
      list[j+1]=k
print(lista)

listb=[6,-8,-3,7,9,35,76,57]
n=len(listb)
for i in range(n):
  for j in range(0,n-i-1):
    if(list[j]>list[j+1]):
      k=list[j]
      list[j]=list[j+1]
      list[j+1]=k
print(listb)


[5, 2, -3.7, 99, 33, 71, 57]
[6, -8, -3, 7, 9, 35, 76, 57]


In [ ]:
a=[5,2,4,1]
for i in range(len(a)):
  for j in range(len(a)-1):
    if a[j]>a[j+1]:
        a[j+1],a[j]=a[j],a[j+1]
print(a)

[1, 2, 4, 5]


In [ ]:
import numpy as np

data2=[[1,2,3,4],[5,6,7,8],[55,66,76,88]]
arr2=np.array(data2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)


2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [55 66 76 88]]


In [ ]:
import numpy as np

data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2.ndim)
print(arr2.shape)

2
(2, 4)


In [ ]:
import numpy as np

data2=[[1,2,3,4]]
arr2=np.array(data2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

2
(1, 4)
[[1 2 3 4]]


In [ ]:
import numpy as np
arr=np.random.randint([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr)
a=3*arr
print(a)
b=a-arr
print(b)

#power of array
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1**3)

#comparison of array
arr2=np.array([[0,4,1],[7,2,12]])
print(arr2)
print(arr2>arr1)

[[ 0  1  1  3]
 [ 3  0  4  6]
 [ 6  5  7  0]
 [ 2  1  4 12]]
[[ 0  3  3  9]
 [ 9  0 12 18]
 [18 15 21  0]
 [ 6  3 12 36]]
[[ 0  2  2  6]
 [ 6  0  8 12]
 [12 10 14  0]
 [ 4  2  8 24]]
[[1 2 3]
 [4 5 6]]
[[  1   8  27]
 [ 64 125 216]]
[[ 0  4  1]
 [ 7  2 12]]
[[False  True False]
 [ True False  True]]
[[ 0  1  0  1]
 [ 1  3  4  0]
 [ 0  2  9  1]
 [12  2 14 15]]
[[ 0  3  0  3]
 [ 3  9 12  0]
 [ 0  6 27  3]
 [36  6 42 45]]
[[ 0  2  0  2]
 [ 2  6  8  0]
 [ 0  4 18  2]
 [24  4 28 30]]
[[1 2 3]
 [4 5 6]]
[[  1   8  27]
 [ 64 125 216]]
[[ 0  4  1]
 [ 7  2 12]]
[[False  True False]
 [ True False  True]]


In [ ]:
array=np.arange(0,10,2)
a

[1, 2, 4, 5]

In [ ]:
ar=np.zeros((2,3))
ar

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
array=np.eye(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
array=np.ones((2,3))
array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr*arr)
print(arr-arr)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr**2)

[[ 1  4  9]
 [16 25 36]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[0,4,1],[7,2,12]])
print(arr2)
print(arr2>arr)

[[ 0  4  1]
 [ 7  2 12]]
[[False  True False]
 [ True False  True]]


In [ ]:
arr=np.array([[1,2,3,6],[4,5,6,8]])
arr2=np.array([[0,4,1,2],[7,2,12,5]])
print(arr2>arr)

[[False  True False False]
 [ True False  True False]]


In [ ]:
import numpy as np
print('Enter the row size')
r=int(input())
print('Enter the column size')
c=int(input())
arr=np.random.randint(0,50,(r,c))
print(arr)

Enter the row size
3
Enter the column size
4
[[27 45 20 29]
 [49 37 18 11]
 [17 46  5 16]]


In [ ]:
import numpy as np
print('Enter the row size')
r=int(input())
print('Enter the column size')
c=int(input())
arr=np.random.randint(0,50,(r,c))
print(arr)
arr1=np.random.randint(0,50,(r,c))
print(arr1)
print(arr>arr1)
print(arr1<arr)


Enter the row size
3
Enter the column size
4
[[33 44 30 19]
 [29 14  9 38]
 [31  7 47 22]]
[[32 39 13 15]
 [ 5 34  1 34]
 [ 0 39 48 38]]
[[ True  True  True  True]
 [ True False  True  True]
 [ True False False False]]
[[ True  True  True  True]
 [ True False  True  True]
 [ True False False False]]


In [ ]:
def merge_sorted_lists(list1, list2):
    merged_list = []
    i = 0
    j = 0

    while i < len(list1) and j < len(list2):
        if list1[i] < list2[j]:
            merged_list.append(list1[i])
            i += 1
        else:
            merged_list.append(list2[j])
            j += 1

    # Append remaining elements from list1, if any
    while i < len(list1):
        merged_list.append(list1[i])
        i += 1

    # Append remaining elements from list2, if any
    while j < len(list2):
        merged_list.append(list2[j])
        j += 1

    return merged_list

# Initialize sorted lists
list1 = [1, 3, 5, 7, 9]
list2 = [2, 4, 6, 8, 10]

# Merge and print the sorted list
merged_list = merge_sorted_lists(list1, list2)
print("Merged Sorted List:", merged_list)

Merged Sorted List: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
def find_second_max_min(nums):
    if len(nums) < 2:
        return None, None

    # Sort the list
    sorted_nums = sorted(nums)

    # Second maximum value
    second_max = sorted_nums[-2]

    # Second minimum value
    second_min = sorted_nums[1]

    return second_max, second_min

# Initialize unsorted list
nums = [9, 3, 7, 1, 5, 8, 2, 6, 4]

# Find second maximum and second minimum values
second_max, second_min = find_second_max_min(nums)

# Print the results
print("Second maximum value:", second_max)
print("Second minimum value:", second_min)

Second maximum value: 8
Second minimum value: 2


In [ ]:
def reverse_list(lst):
    reversed_lst = []
    # Iterate through the list in reverse order and append elements to the new list
    for i in range(len(lst) - 1, -1, -1):
        reversed_lst.append(lst[i])
    return reversed_lst

# Initialize the list
original_list = [1, 2, 3, 4, 5]

# Reverse the list
reversed_list = reverse_list(original_list)

# Print the reversed list
print("Original List:", original_list)
print("Reversed List:", reversed_list)

Original List: [1, 2, 3, 4, 5]
Reversed List: [5, 4, 3, 2, 1]


In [ ]:
import numpy as np

def compare_arrays(array1, array2):
    # Check if the arrays have the same shape
    if array1.shape != array2.shape:
        return "Arrays have different shapes."

    # Compare element-wise
    comparison_result = np.equal(array1, array2)

    return comparison_result

# Generate two n-dimensional arrays
n = 3  # You can change this value to generate arrays of different dimensions
array1 = np.random.randint(0, 10, size=(n, n, n))
array2 = np.random.randint(0, 10, size=(n, n, n))

# Compare arrays
result = compare_arrays(array1, array2)

# Print the comparison result
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nComparison Result:")
print(result)

Array 1:
[[[0 3 2]
  [8 6 6]
  [1 3 7]]

 [[7 6 8]
  [9 9 0]
  [1 6 6]]

 [[7 1 6]
  [8 0 9]
  [2 3 0]]]

Array 2:
[[[2 7 9]
  [7 9 2]
  [0 2 3]]

 [[9 8 1]
  [2 1 0]
  [1 5 3]]

 [[1 5 4]
  [5 9 0]
  [0 7 0]]]

Comparison Result:
[[[False False False]
  [False False False]
  [False False False]]

 [[False False False]
  [False False  True]
  [ True False False]]

 [[False False False]
  [False False False]
  [False False  True]]]


In [ ]:
def gcd_fun(x,y):
  if(y==0):# it divide every number
    return x # returnx
  else:
    return gcd_fun(y,x % y)
x=int(input("Enter the first number:"))# take first no.
y=int(input("Enter the second number:"))# take second no.
num=gcd_fun(x,y) # call the gcd_fun() to find result
print("GCD of two number is:")
print(num)# call num

Enter the first number:6
Enter the second number:8
GCD of two number is:
2


In [11]:
def linear_search(list1,n,key):

  #Searching list1 sequentially
   for i in range(0,n):
    if (list1[1]==key):
       return 1
    return-1


list1=[1,3,5,4,7,9]
key=7

n=len(list1)
res=linear_search(list1,n,key)
if(res==-1):
  print("Element not found:")
else:
  print("Element found at index:",res)


Element not found:


In [ ]:
def binary_search(list1,n):
 low=0
 high=len(list1)-1
 mid=0
 while (low<=high):
  # for get integer result
  mid=(high+low)//2
    # Check if n is present at mid
 if list1[mid]<n:
    low=mid+1
    # if n is greater,compare to the right of mid
 elif list1[mid]>n:
    high=mid-1
    # if n is smaller,compare to the left of mid
 else:
   return mid
      # Element was not present in the list,return-1
   return-1
# Initial list 1
list1=[12,24,32,39,45,50,54]
n=45
# Function call
result=binary_search(list1,n)
if result !=-1:
  print("Element is present at index",str(result))
else:
  print("Element is not present in list1")